// Tips.js
const Tips = [
    { id: 1, text: "Plan your meals ahead to avoid buying excess groceries." },
    { id: 2, text: "Store food properly to prolong its freshness." },
    { id: 3, text: "Use leftovers creatively in new dishes." },
    { id: 4, text: "Compost food scraps instead of throwing them away." },
    { id: 5, text: "Shop with a list to avoid impulse purchases." },
    { id: 6, text: "Check expiration dates before purchasing food items." },
    { id: 7, text: "Buy in bulk for items you use frequently to reduce packaging waste." },
    { id: 8, text: "Grow your own herbs and vegetables to reduce food packaging and waste." },
    { id: 9, text: "Donate excess non-perishable food items to local food banks." },
    { id: 10, text: "Support businesses that prioritize sustainability and reducing food waste." },
    { id: 11, text: "Use reusable containers for packed lunches and leftovers." },
    { id: 12, text: "Buy misshapen or imperfect produce to help reduce food waste." },
    { id: 13, text: "Learn to properly freeze food to extend its shelf life." },
    { id: 14, text: "Cook vegetable scraps (like carrot tops and celery leaves) to make flavorful broths." },
    { id: 15, text: "Educate yourself about portion sizes to avoid over-serving food." },
    { id: 16, text: "Use citrus peels to make homemade cleaners." },
    { id: 17, text: "Revive wilted vegetables by soaking them in ice water." },
    { id: 18, text: "Repurpose glass jars for storing grains, nuts, and other pantry items." },
    { id: 19, text: "Shop at farmers' markets to support local growers and reduce food miles." },
    { id: 20, text: "Create a meal plan based on ingredients you already have to minimize waste." },
    { id: 21, text: "Store bread in the freezer to prevent it from going stale." },
    { id: 22, text: "Use overripe bananas to make banana bread or smoothies." },
    { id: 23, text: "Revitalize stale chips and crackers by baking them in the oven for a few minutes." },
    { id: 24, text: "Learn to preserve foods through methods like pickling and canning." },
    { id: 25, text: "Keep track of perishable items in your fridge with a 'use first' section." },
    { id: 26, text: "Use vegetable peels and scraps to make compost for your garden." },
    { id: 27, text: "Use reusable shopping bags and produce bags to reduce plastic waste." },
    { id: 28, text: "Try to shop at zero-waste grocery stores when possible." },
    { id: 29, text: "Cook with bones and vegetable scraps to make flavorful homemade stocks." },
    { id: 30, text: "Buy imperfect fruits and vegetables to help reduce food waste at the farm level." },
    { id: 31, text: "Repurpose stale bread to make croutons, breadcrumbs, or bread pudding." },
    { id: 32, text: "Avoid overbuying perishable items by shopping more frequently." },
    { id: 33, text: "Share leftovers with friends or neighbors to prevent food waste." },
    { id: 34, text: "Use a compost bin to turn food scraps into nutrient-rich soil for your garden." },
    { id: 35, text: "Use reusable silicone lids or beeswax wraps instead of plastic cling film." },
    { id: 36, text: "Learn to properly store different types of produce to maximize freshness." },
    { id: 37, text: "Cook with whole ingredients to reduce packaging waste from processed foods." },
    { id: 38, text: "Try meatless meals a few times a week to reduce your carbon footprint." },
    { id: 39, text: "Turn fruit that's starting to go soft into smoothies or fruit salads." },
    { id: 40, text: "Invest in a vacuum sealer to extend the shelf life of food items." },
    { id: 41, text: "Reuse cooking water from boiled vegetables as a base for soups or sauces." },
    { id: 42, text: "Create a 'leftover night' meal once a week to use up any remaining food items." },
    { id: 43, text: "Keep track of what's in your pantry and fridge to avoid buying duplicates." },
    { id: 44, text: "Save vegetable scraps for homemade vegetable broth." },
    { id: 45, text: "Use wilted herbs to make herb-infused oils or vinegars." },
    { id: 46, text: "Use a meal planning app to help reduce overbuying and food waste." },
    { id: 47, text: "Repurpose leftover pasta into pasta salad or frittata." },
    { id: 48, text: "Store delicate greens like lettuce and spinach in a paper towel to absorb excess moisture." },
    { id: 49, text: "Repurpose leftover rice into fried rice or rice pudding." },
    { id: 50, text: "Donate excess canned goods and non-perishable items to food drives." },
    
  ];
  
  export default Tips;
  
  